### ISSUE TITLE
Run command.

### ISSUE THREAD

**Issue by inakimalerba** [amki/docker-teamspeak-client#1]
Could you please add the run command, to know which volumes should be shared? 

Thanks

**Comment by amki** [comment]
Which directories do you want to share? There is nothing you'd want to migrate between containers I guess. It's the client not the server.

**Comment by inakimalerba** [comment]
I mean, you should pass the x server and audio right?

**Comment by amki** [comment]
The X (Xvfb) and pulseaudio servers are encapsulated inside the container so you can run multiple containers without them interfering. It's possible to at least have the pulseaudio server exposed to the host but this Dockerfile doesn't support it and I don't know enough about pulseaudio to implement this without quite a bit of research.

**Comment by inakimalerba** [comment]
So how do you run it? WIth `docker run` the stdout shows that it started but nothing happens

**Comment by Kudlaty01** [comment]
Hello,
has this been fixed by any way?
